# -*- coding: utf-8 -*-
"""stock-trader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbxcqmTn-0yQSsFMnI8XzfJheo3olU7y
"""

# ==========================================
# 老陳 AI 交易系統 V15.0 - 價量籌碼全能版
# 新增：MFI (資金流向指標) + 成交量異動偵測
# ==========================================

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(page_title="老陳價量分析 V15", layout="wide", page_icon="💰")

# --- 1. 核心計算函數 (含 MFI 與 OBV) ---
@st.cache_data(ttl=60)
def get_data_v15(symbol):
    try:
        df = yf.download(symbol, period='6mo', interval='1d', progress=False, auto_adjust=False)
        if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)
        df = df.apply(pd.to_numeric, errors='coerce').dropna()

        # === A. 基礎指標 ===
        df['MA20'] = df['Close'].rolling(window=20).mean()
        df['MA60'] = df['Close'].rolling(window=60).mean()

        # === B. 成交量分析 (Volume Analysis) ===
        # 計算成交量平均線 (VMA)
        df['Vol_MA20'] = df['Volume'].rolling(window=20).mean()
        # 爆量係數：今天成交量是平均的幾倍？
        df['Vol_Ratio'] = df['Volume'] / df['Vol_MA20']

        # === C. 資金流指標 (Money Flow Index - MFI) ===
        # MFI 類似 RSI，但它把成交量也算進去，比 RSI 更準
        typical_price = (df['High'] + df['Low'] + df['Close']) / 3
        money_flow = typical_price * df['Volume']

        # 判斷正向流還是負向流
        positive_flow = np.where(typical_price > typical_price.shift(1), money_flow, 0)
        negative_flow = np.where(typical_price < typical_price.shift(1), money_flow, 0)

        # 14天加總
        pos_mf_sum = pd.Series(positive_flow).rolling(window=14).sum()
        neg_mf_sum = pd.Series(negative_flow).rolling(window=14).sum()

        # 計算 MFI
        mfi_ratio = pos_mf_sum / neg_mf_sum
        df['MFI'] = 100 - (100 / (1 + mfi_ratio))
        # 補回索引 (因為 np.where 會丟失索引)
        df['MFI'].index = df.index

        # === D. KDJ (保留之前的 J線神器) ===
        low_list = df['Low'].rolling(9, min_periods=9).min()
        high_list = df['High'].rolling(9, min_periods=9).max()
        rsv = (df['Close'] - low_list) / (high_list - low_list) * 100
        df['K'] = rsv.ewm(com=2, adjust=False).mean()
        df['D'] = df['K'].ewm(com=2, adjust=False).mean()
        df['J'] = 3 * df['K'] - 2 * df['D']

        return df.dropna()
    except Exception as e:
        return None

def analyze_volume_money(df):
    last = df.iloc[-1]
    prev = df.iloc[-2]

    score = 0
    signals = []

    # 1. 資金流 (MFI) 分析
    if last['MFI'] > 80:
        score -= 2
        signals.append("💰 MFI 資金超買 (>80) - 大戶可能在出貨")
    elif last['MFI'] < 20:
        score += 2
        signals.append("💰 MFI 資金超賣 (<20) - 地板價，沒人肯賣了")

    # MFI 背馳 (高階技巧)：股價創新高，MFI 卻沒創新高
    if last['Close'] > prev['Close'] and last['MFI'] < prev['MFI'] and last['MFI'] > 60:
        score -= 1
        signals.append("⚠️ 頂背馳 (價升資金流出) - 小心假突破")

    # 2. 成交量 (Volume) 分析
    if last['Vol_Ratio'] > 2.0: # 今天量是平常 2倍
        if last['Close'] > last['Open']:
            score += 1
            signals.append("🔥 爆量長陽 (Vol > 2x) - 大資金進場")
        else:
            score -= 1
            signals.append("💀 爆量長陰 (Vol > 2x) - 大資金恐慌出逃")
    elif last['Vol_Ratio'] < 0.5:
        signals.append("💤 縮量 (Vol < 0.5x) - 市場觀望")

    # 3. 價量關係 (Price-Volume Action)
    # 價升量升 = 好
    if last['Close'] > prev['Close'] and last['Volume'] > prev['Volume']:
        score += 1
        signals.append("📈 價量齊升 (健康上漲)")
    # 價升量跌 = 虛
    elif last['Close'] > prev['Close'] and last['Volume'] < prev['Volume']:
        signals.append("⚠️ 縮量上漲 (乾升) - 動力不足")

    # 4. 趨勢與 J線 (輔助)
    if last['J'] < 10 and last['J'] > prev['J']:
        score += 1; signals.append("⚡ J線低位勾頭")
    if last['Close'] > last['MA20']:
        score += 1

    return score, signals

# --- 2. 介面 ---
st.title("💰 老陳 AI - 價量籌碼分析系統 (V15)")

col1, col2 = st.columns([3, 1])
with col1:
    symbol = st.text_input("股票代號 (如 0700.HK, NVDA)", value="^HSI").upper()
with col2:
    if st.button("深度分析"): st.rerun()

df = get_data_v15(symbol)

if df is not None:
    last = df.iloc[-1]
    change = last['Close'] - df.iloc[-2]['Close']

    # 頂部數據卡
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("現價", f"{last['Close']:,.2f}", f"{change:+.2f}")
    c2.metric("成交量 (Vol)", f"{last['Volume']/1e6:.1f}M", f"x{last['Vol_Ratio']:.1f}倍")
    c3.metric("資金流指標 (MFI)", f"{last['MFI']:.1f}")
    c4.metric("J線 (轉勢)", f"{last['J']:.1f}")

    # 分析結果
    score, signals = analyze_volume_money(df)

    st.markdown("---")
    st.subheader("🤖 AI 價量診斷")
    if score >= 4:
        st.success("🚀 強力買入 (Strong Buy) - 量能充沛 + 資金進場")
    elif score <= -3:
        st.error("💥 強力賣出 (Strong Sell) - 爆量下殺 + 資金出逃")
    elif score > 0:
        st.info("👀 偏好 (Weak Buy)")
    else:
        st.warning("👀 偏淡 (Weak Sell)")

    with st.expander("查看【量 & 錢】詳細解讀"):
        for s in signals: st.write(s)

    # --- 專業 4 層圖表 ---
    st.subheader("📊 綜合操盤圖")

    # 建立 4 層圖表: 價格, 成交量, MFI資金, J線
    fig = make_subplots(rows=4, cols=1, shared_xaxes=True,
                        vertical_spacing=0.03, row_heights=[0.4, 0.2, 0.2, 0.2],
                        subplot_titles=('價格 & MA', '成交量 (Volume)', '資金流向 (MFI)', 'KDJ (J線)'))

    # [1] 價格 K線
    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'],
                                 low=df['Low'], close=df['Close'], name='Price'), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['MA20'], line=dict(color='orange', width=1), name='MA20'), row=1, col=1)

    # [2] 成交量 (紅綠柱)
    colors_vol = ['#00cc96' if c >= o else '#ef553b' for c, o in zip(df['Close'], df['Open'])]
    fig.add_trace(go.Bar(x=df.index, y=df['Volume'], marker_color=colors_vol, name='Volume'), row=2, col=1)
    # 加上 20日平均量線
    fig.add_trace(go.Scatter(x=df.index, y=df['Vol_MA20'], line=dict(color='white', width=1, dash='dot'), name='Vol MA20'), row=2, col=1)

    # [3] MFI 資金流
    fig.add_trace(go.Scatter(x=df.index, y=df['MFI'], line=dict(color='#00bfff', width=2), name='MFI (資金)'), row=3, col=1)
    # 畫出資金超買超賣區
    fig.add_hline(y=80, line_dash="dot", row=3, col=1, line_color="red")
    fig.add_hline(y=20, line_dash="dot", row=3, col=1, line_color="green")
    # 填色顯示區域
    # (Plotly fill 比較複雜，這裡用簡單線條表示即可)

    # [4] J線
    fig.add_trace(go.Scatter(x=df.index, y=df['J'], line=dict(color='#ab63fa', width=2), name='J線'), row=4, col=1)
    fig.add_hline(y=100, line_dash="dot", row=4, col=1, line_color="red")
    fig.add_hline(y=0, line_dash="dot", row=4, col=1, line_color="green")

    fig.update_layout(height=1000, xaxis_rangeslider_visible=False, showlegend=False, template="plotly_dark")
    st.plotly_chart(fig, use_container_width=True)

else:
    st.error("找不到數據，請確認代號。")